/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.HoaDonThuePhong_DAO;
import dao.KhachHang_DAO;
import entity.KhachHang;
import java.awt.Font;
import java.awt.BorderLayout;

/**
 *
 * @author ADMIN
 */
public class JPanel_ThongKeKHTiemNang extends javax.swing.JPanel {
	private DefaultTableModel modelKHTN;
	private HoaDonThuePhong_DAO hoaDonThuePhong_DAO;
	private KhachHang_DAO khachHang_DAO;
	private JPanel[] pnlThonKeKH;
	private JLabel[] lblTieuDe;
	private JLabel[] lblTenKhachHangs;
	private JLabel[] lblTongSoTiens;
	private JLabel txtTienThuNhat;
	private JLabel txtTenThu1;
	private JLabel txtTenThu2;
	private JLabel txtTienThu2;
	
	
    /**
     * Creates new form ThongKeKhachHangTiemNang
     */
    public JPanel_ThongKeKHTiemNang() {
        initComponents();
      
        modelKHTN = (DefaultTableModel) tblKHTiemNang.getModel();
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		khachHang_DAO = new KhachHang_DAO(); 
		hoaDonThuePhong_DAO = new HoaDonThuePhong_DAO();
		DocDuLieuDatabaseVaoTable();
//		 pnlThongSoThongKe.setLayout(null);
//		
//		 pnlThongSoThongKe.setLayout(new GridLayout(1, 3));
//	        pnlThonKeKH = new JPanel[5];
//	        lblTieuDe = new JLabel[5];
//	        lblTenKhachHangs = new JLabel[5];
//	        lblTongSoTiens = new JLabel[5];
//	        for (int i = 0; i < 3; i++) {
//	        	pnlThonKeKH[i] = new JPanel();
//	        	lblTieuDe[i] = new JLabel();
//	        	lblTenKhachHangs[i] = new JLabel();
//	        	lblTongSoTiens[i] = new JLabel();
//	        	
//	        	pnlThonKeKH[i].setLayout(null);
//	        	pnlThonKeKH[i].setPreferredSize(new Dimension(100, 100));
////	        	pnlThonKeKH[i].setAlignmentX(Component.CENTER_ALIGNMENT);
//	        	pnlThonKeKH[i].setBounds(300, 500, 135, 135);
////	        	pnlThonKeKH[i].setBackground(new Color(255, 255, 255));
//	        	lblTieuDe[i].setText("Khách hang tiềm năng" + i+1);
//	        	lblTieuDe[i].setBounds(300, 500, 135, 135);
//	        	
//	        	pnlThonKeKH[i].add(lblTieuDe[i]);
//	        	pnlThongSoThongKe.add(pnlThonKeKH[i]);
//	        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlKHTiemNang = new javax.swing.JPanel();
        pnlThongSoThongKe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKHTiemNang = new javax.swing.JTable();

        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 750));

        pnlKHTiemNang.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Khách Hàng Tiềm Năng"));

        pnlThongSoThongKe.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongSoThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Số Thống Kê"));

        tblKHTiemNang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            	
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng ", "Số Điện Thoại ", "Thời Gian Sử Dụng ", "Số Lần Sử Dụng", "Thành Tiền (VNĐ) "
            }
        ));
        tblKHTiemNang.setShowGrid(true);
        jScrollPane1.setViewportView(tblKHTiemNang);
       
        
        javax.swing.GroupLayout pnlKHTiemNangLayout = new javax.swing.GroupLayout(pnlKHTiemNang);
        pnlKHTiemNangLayout.setHorizontalGroup(
        	pnlKHTiemNangLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlKHTiemNangLayout.createSequentialGroup()
        			.addGroup(pnlKHTiemNangLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlKHTiemNangLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1110, GroupLayout.PREFERRED_SIZE))
        				.addComponent(pnlThongSoThongKe, GroupLayout.PREFERRED_SIZE, 1158, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKHTiemNangLayout.setVerticalGroup(
        	pnlKHTiemNangLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlKHTiemNangLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 480, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(pnlThongSoThongKe, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        pnlThongSoThongKe.setLayout(null);
        
        JPanel panel = new JPanel();
        panel.setBounds(22, 26, 499, 119);
        pnlThongSoThongKe.add(panel);
        panel.setLayout(new BorderLayout(0, 0));
        
        JLabel lblKHThuNhat = new JLabel("Khách Hàng Tiềm Năng Nhất");
        lblKHThuNhat.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(lblKHThuNhat, BorderLayout.NORTH);
        lblKHThuNhat.setFont(new Font("Tahoma", Font.BOLD, 19));
        
        txtTienThuNhat = new JLabel("0");
        txtTienThuNhat.setForeground(new Color(255, 0, 0));
        txtTienThuNhat.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(txtTienThuNhat, BorderLayout.SOUTH);
        txtTienThuNhat.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        txtTenThu1 = new JLabel("kh");
        txtTenThu1.setForeground(new Color(255, 0, 0));
        txtTenThu1.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(txtTenThu1, BorderLayout.CENTER);
        txtTenThu1.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        JPanel panel_1 = new JPanel();
        panel_1.setBounds(602, 26, 522, 119);
        pnlThongSoThongKe.add(panel_1);
        panel_1.setLayout(new BorderLayout(0, 0));
        
        JLabel lblKH = new JLabel("Khách Hàng Trung Thành Nhất");
        lblKH.setHorizontalAlignment(SwingConstants.CENTER);
        panel_1.add(lblKH, BorderLayout.NORTH);
        lblKH.setFont(new Font("Tahoma", Font.BOLD, 20));
        
        txtTenThu2 = new JLabel("kh");
        txtTenThu2.setForeground(new Color(255, 0, 0));
        txtTenThu2.setHorizontalAlignment(SwingConstants.CENTER);
        txtTenThu2.setFont(new Font("Tahoma", Font.BOLD, 20));
        panel_1.add(txtTenThu2, BorderLayout.CENTER);
        
        txtTienThu2 = new JLabel("0");
        txtTienThu2.setForeground(new Color(255, 0, 0));
        txtTienThu2.setHorizontalAlignment(SwingConstants.CENTER);
        txtTienThu2.setFont(new Font("Tahoma", Font.BOLD, 21));
        panel_1.add(txtTienThu2, BorderLayout.SOUTH);
        pnlKHTiemNang.setLayout(pnlKHTiemNangLayout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(pnlKHTiemNang, GroupLayout.PREFERRED_SIZE, 1170, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pnlKHTiemNang, GroupLayout.PREFERRED_SIZE, 701, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1196, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 765, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    public void DocDuLieuDatabaseVaoTable() {
    	modelKHTN.setRowCount(0);
    	List<KhachHang> list = khachHang_DAO.getKhachHangTiemNang();
    	DecimalFormat formatter = new DecimalFormat("###,###,###");
    	for (KhachHang kh : list) {
			Object [] row = {kh.getMaKhachHang(),kh.getTenKhachHang(),kh.getSoDienThoai(), 
					khachHang_DAO.getThoiGianSuDungTheoMa(kh.getMaKhachHang()) ,
					khachHang_DAO.getSoLanDenTheoMa(kh.getMaKhachHang()), 
					formatter.format(khachHang_DAO.getTongHoaDonTheoMa(kh.getMaKhachHang()))};
			modelKHTN.addRow(row);
    	}
    	
    	// Khai báo biến để lưu trữ thông tin của top1, top2, top3
    	KhachHang top1 = null;
    	KhachHang top2 = null;

    	double max1 = Double.MIN_VALUE;
    	double max2 = Double.MIN_VALUE;
    	
    	KhachHang topDenCaoNhat = null;
    	int maxDenCaoNhat = Integer.MIN_VALUE;
    	
    	for (KhachHang kh : list) {
    	    double tongHoaDon = khachHang_DAO.getTongHoaDonTheoMa(kh.getMaKhachHang());
    	    int soLanDen = khachHang_DAO.getSoLanDenTheoMa(kh.getMaKhachHang());

    	    if (tongHoaDon > max1) {
    	        max2 = max1;
    	        max1 = tongHoaDon;

    	        top2 = top1;
    	        top1 = kh;
    	    } 
    	    
    	    if (soLanDen > maxDenCaoNhat) {
    	        maxDenCaoNhat = soLanDen;
    	        topDenCaoNhat = kh;
    	    }
    	}

    	// Hiển thị thông tin lên giao diện sau khi đã xác định được top1, top2, top3
    	txtTenThu1.setText(top1 != null ? top1.getTenKhachHang() : "");
    	txtTienThuNhat.setText(top1 != null ? formatter.format(max1) + " VNĐ" : "");
    	txtTenThu2.setText(topDenCaoNhat != null ? topDenCaoNhat.getTenKhachHang() : "");
    	txtTienThu2.setText(topDenCaoNhat != null ? String.valueOf(maxDenCaoNhat) + " lần" : "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlKHTiemNang;
    private javax.swing.JPanel pnlThongSoThongKe;
    private javax.swing.JTable tblKHTiemNang;
}
