/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import connectDB.ConnectDB;
import dao.LoaiPhong_DAO;
import dao.NhanVien_DAO;
import dao.Phong_DAO;
import entity.LoaiPhong;
import entity.NhanVien;
import entity.PhongHat;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class JPanel_DanhMucNhanVien extends javax.swing.JPanel implements MouseListener,ActionListener
{
	 private NhanVien_DAO nhanVien_dao;
	 private ArrayList<NhanVien> listNhanVien;
	 private DefaultTableModel mode_NhanVien;

    /**
     * Creates new form NewJPanel
     */
    public JPanel_DanhMucNhanVien() {
    	try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		nhanVien_dao = new NhanVien_DAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblma = new javax.swing.JLabel();
        lblngaySinh = new javax.swing.JLabel();
        lblhoTen = new javax.swing.JLabel();
        lblgioiTinh = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        lblsoDienThoai = new javax.swing.JLabel();
        lbldiaChi = new javax.swing.JLabel();
        lbltrangThai = new javax.swing.JLabel();
        lbltitleDanhSach = new javax.swing.JLabel();
        lblchucVu = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        cbbChucVu = new javax.swing.JComboBox<>();
        JDateNgaySinh = new com.toedter.calendar.JDateChooser();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lblTim = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 217, 217));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1250, 755));

        lblma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblma.setLabelFor(lblma);
        lblma.setText("Mã nhân viên :");

        lblngaySinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblngaySinh.setText("Ngày sinh :");

        lblhoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblhoTen.setText("Tên nhân viên :");

        lblgioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblgioiTinh.setText("Giới tính :");

        lblCCCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCCCD.setText("CCCD :");

        lblsoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsoDienThoai.setText("Số điện thoại :");

        lbldiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldiaChi.setText("Địa chỉ :");

        lbltrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltrangThai.setText("Trạng thái :");

        lbltitleDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltitleDanhSach.setText("Danh sách nhân viên");

        lblchucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblchucVu.setText("Chức vụ :");

        txtMa.setEditable(false);
        txtMa.setBackground(new java.awt.Color(204, 204, 204));
        txtMa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMa.setPreferredSize(new java.awt.Dimension(64, 25));
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        txtTen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTen.setPreferredSize(new java.awt.Dimension(64, 25));

        txtSDT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSDT.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtDiaChi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDiaChi.setPreferredSize(new java.awt.Dimension(64, 25));

        txtCCCD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCCCD.setPreferredSize(new java.awt.Dimension(64, 25));

        txtTrangThai.setEditable(false);
        txtTrangThai.setBackground(new java.awt.Color(204, 204, 204));
        txtTrangThai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTrangThai.setPreferredSize(new java.awt.Dimension(64, 25));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(51, 51, 51));
        btnThem.setIcon(new javax.swing.ImageIcon("item/add25.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.setPreferredSize(new java.awt.Dimension(110, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhap.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCapNhap.setIcon(new javax.swing.ImageIcon("item/update25.png")); // NOI18N
        btnCapNhap.setText("Cập nhập");
        btnCapNhap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCapNhap.setPreferredSize(new java.awt.Dimension(110, 30));
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("item/refresh25.png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(110, 30));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        table.setFont(new Font("Segoe UI", Font.PLAIN, 15)); // NOI18N
        table.setModel(mode_NhanVien = new DefaultTableModel(
            new Object [][] {
               
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "CCCD", "Chức vụ ", "Trạng thái", "Số điện thoại", "Địa chỉ"
            }
        ));
        table.setGridColor(new Color(0, 0, 255));
        table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(table);

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setPreferredSize(new java.awt.Dimension(72, 20));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên ", "Quản lý" }));
        cbbChucVu.setPreferredSize(new java.awt.Dimension(72, 20));
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });

        JDateNgaySinh.setPreferredSize(new java.awt.Dimension(88, 25));
        txtTim.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTim.setPreferredSize(new java.awt.Dimension(64, 25));
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(51, 51, 51));
        btnTim.setText("Tìm");
        btnTim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTim.setPreferredSize(new java.awt.Dimension(110, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });

        lblTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTim.setText("Tìm theo mã");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitleDanhSach)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblma)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                        .addComponent(btnCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbldiaChi)
                                        .addGap(68, 68, 68)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblhoTen)
                                    .addComponent(lblngaySinh)
                                    .addComponent(lblgioiTinh)
                                    .addComponent(lblsoDienThoai))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCCCD)
                                    .addComponent(lbltrangThai)
                                    .addComponent(lblchucVu))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblgioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblchucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                
                .addComponent(lbltitleDanhSach)
            
                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
//            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                    .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                        .addComponent(txtTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(lblTim)))
            	
        );
        loadNhanVien();
        table.addMouseListener(this);

    }// </editor-fold>//GEN-END:initComponents
    public void loadNhanVien() {
		listNhanVien = nhanVien_dao.getAllNhanVien();
		
		for (NhanVien nv: listNhanVien) {
			String gt ="Nữ";
			if(nv.getGioiTinh()==1) {
				gt ="Nam";
			}
			mode_NhanVien.addRow(new Object[] { 
					nv.getMaNhanVien(), nv.getTenNhanVien() ,
					nv.getNgaySinh(),gt,
					nv.getcCCD(), nv.getChucVu(),nv.getTrangThai(), 
					nv.getSoDienThoai(),nv.getDiaChi() });
		}
	}
 // Check dữ liệu
 	Border bdFalse = BorderFactory.createLineBorder(Color.red);
 	Border bdTrue = BorderFactory.createLineBorder(Color.green);
    // kiểm tra thông tin nhập vào 
    public boolean validData() {
		// TODO Auto-generated method stub
		String ten = txtTen.getText().trim();

		if (ten.length() > 0 || !ten.equals("")) {
			if (!ten.matches("^[a-zA-Z0-9\\- _\\.\\'\\u0300-\\u0309\\u0323-\\u0326]+$")) {
				JOptionPane.showMessageDialog(this, "Error: Tên nhân viên phải chứa các ký tự chữ cái và dấu cách: VD( Nguyễn Văn A )");
				txtTen.requestFocus(true);
				txtTen.setBorder(bdFalse);
				return false;
			} else {
				txtTen.setBorder(bdTrue);
			}
		} else {
			JOptionPane.showMessageDialog(this, "Error: Chưa nhập tên nhân viên!");
			txtTen.requestFocus(true);
			txtTen.setBorder(bdFalse);
			return false;
		}
		return true;
    }
    public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		int r = table.getSelectedRow();
		txtMa.setText(mode_NhanVien.getValueAt(r, 0).toString());
		txtTen.setText(mode_NhanVien.getValueAt(r, 1).toString());
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
		Date date = null;
		try {
			date = format.parse(mode_NhanVien.getValueAt(r, 2).toString());
		} catch (ParseException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		JDateNgaySinh.setDate(date);
		cbbGioiTinh.setSelectedItem(mode_NhanVien.getValueAt(r, 3));
		txtCCCD.setText(mode_NhanVien.getValueAt(r, 4).toString());
		cbbChucVu.setSelectedItem(mode_NhanVien.getValueAt(r, 5));
		txtTrangThai.setText(mode_NhanVien.getValueAt(r, 6).toString());
		txtSDT.setText(mode_NhanVien.getValueAt(r, 7).toString());
		txtDiaChi.setText(mode_NhanVien.getValueAt(r, 8).toString());
		requestFocus();
		
		
		
	}

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    	addnew_Phong();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    	lamMoi();
    	
    }//GEN-LAST:event_btnLamMoiActionPerformed
    public void lamMoi() {
    	txtMa.setText("");
    	txtTen.setText("");
    	txtCCCD.setText("");
    	txtTrangThai.setText("");
    	JDateNgaySinh.setDate(null);
    	txtSDT.setText("");
    	txtDiaChi.setText("");
    	cbbGioiTinh.setSelectedIndex(0);
    	cbbChucVu.setSelectedIndex(0);
    	mode_NhanVien.setRowCount(0);
    	txtTen.requestFocus();
    	loadNhanVien();
    	
    }
    // phát sinh mã nhan vien
   	public String generateCode() {
           // Khởi tạo một biến để lưu trữ mã
           String maNhanVien = "";
           String prefix;
           // Tạo một biến ngẫu nhiên
           Random random = new Random();

           // Lấy ngẫu nhiên một tiền tố
           String loaiPhong = cbbChucVu.getSelectedItem().toString();
           if (loaiPhong.equalsIgnoreCase("Quản Lý"))
           	prefix = "QL";
           else 
           	prefix = "NV";

           // Tạo một chuỗi gồm 3 số ngẫu nhiên
           for (int i = 0; i < 3; i++) {
           	maNhanVien += random.nextInt(10);
           }

           return prefix + maNhanVien;
       }
    // tạo 1 nhan vien
  	public NhanVien revertNhanVien() {
  		// TODO Auto-generated method stub
  		String ma = generateCode();
  		int count = nhanVien_dao.kiemTraMa(ma);
  		
		if (count > 0) {
			ma = generateCode();
		}
  		int gt;
 		String ten = txtTen.getText().trim();
 		String cccd = txtCCCD.getText().trim();
 		String trangThai = txtTrangThai.getText().trim();
 		Date ns = JDateNgaySinh.getDate();
 		String sdt = txtSDT.getText().trim();
 		String dc = txtDiaChi.getText().trim();
 		String gioi = cbbGioiTinh.getSelectedItem().toString();
 		if(gioi=="Nam") {
 			gt =1;
 		}
 		else {
 			gt = 0;
 		}
 		String cv = cbbChucVu.getSelectedItem().toString();
  		return new 	NhanVien(ma,ten,ns,sdt,cccd,gt,dc,cv,trangThai);
  	}
 // thêm nhan vien
 	private void addnew_Phong() {
// 		if (validData()) {
 			NhanVien nv = revertNhanVien();
 			nhanVien_dao.addNhanVien(nv);
 			JOptionPane.showMessageDialog(this, "Thêm thành công!");
 			mode_NhanVien.setRowCount(0);
 			loadNhanVien();
 			lamMoi();;
// 		}
 	}
 // cập nhật 1 nhan vien
 	public NhanVien update_NhanVien(String ma) {
 		int gt;
 		String ten = txtTen.getText().trim();
 		String cccd = txtCCCD.getText().trim();
 		String trangThai = txtTrangThai.getText().trim();
 		Date ns = JDateNgaySinh.getDate();
 		String sdt = txtSDT.getText().trim();
 		String dc = txtDiaChi.getText().trim();
 		String gioi = cbbGioiTinh.getSelectedItem().toString();
 		if(gioi=="Nam") {
 			gt =1;
 		}
 		else {
 			gt = 0;
 		}
 		String cv = cbbChucVu.getSelectedItem().toString();
 		
// 		if()
 	
 		return new 	NhanVien(ma,ten,ns,sdt,cccd,gt,dc,cv,trangThai);
 		
 	}
    public void edit_NhanVien() {
 		int row = table.getSelectedRow();
 		if (txtMa.getText().equals("")) {
 			JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên để cập nhật thông tin!");
 		} else {
 			int choice = JOptionPane.showConfirmDialog(null, "Ban có chắc chắn muốn cập nhật không ?");
 			if (choice == JOptionPane.YES_OPTION) {
// 				if (validData()) {
 					String ma = txtMa.getText().trim();
 					NhanVien nv = update_NhanVien(ma);

 					nhanVien_dao.capNhat_NhanVien(nv);
 					lamMoi();
 					JOptionPane.showMessageDialog(null, "Cập nhật hoàn tất!");
// 				}
 			}
 		}
 	}
 	// gan su kien cap nhap nhan vien
    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // TODO add your handling code here:
    	edit_NhanVien();
    	
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucVuActionPerformed

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioiTinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateNgaySinh;
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblchucVu;
    private javax.swing.JLabel lbldiaChi;
    private javax.swing.JLabel lblgioiTinh;
    private javax.swing.JLabel lblhoTen;
    private javax.swing.JLabel lblma;
    private javax.swing.JLabel lblngaySinh;
    private javax.swing.JLabel lblsoDienThoai;
    private javax.swing.JLabel lbltitleDanhSach;
    private javax.swing.JLabel lbltrangThai;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTrangThai;
	private javax.swing.JTextField txtTim;
	private javax.swing.JButton btnTim;
	private javax.swing.JLabel lblTim;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
}
